### ISSUE TITLE
Xây dựng  cấu trúc khung

### ISSUE THREAD

**Issue by nguago** [viisystem/viisystem#5]

**Comment by minhnguyenerp** [comment]
Cái viisystem sẽ đóng vai trò là cái core, cần tạo thêm cái viisystem-cms sẽ là phần về cms. Tương tự như thằng này https://github.com/noumo, easyii-start, easyii-shop sẽ required easyii.

Để nghiên cứu thêm một chút rồi sẽ create json rồi test cấu trúc như nào cho hợp lý
